/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <TrafficLight.h>
#include "stm32f1xx_hal.h"

unsigned int LightState,LightGreenTimeOn,LightYellowTimeOn,LightRedTimeOn,TimeNeedToDisplay;

void TrafficLightRunAtAdjust(void);

void TrafficLightRunAtNormal(void);

void TrafficLightInit(void)
{
    LightState = 0;
    LightGreenTimeOn = LIGHT_GREEN_TIME_ON_DEFAULT;
    LightYellowTimeOn = LIGHT_YELLOW_TIME_ON_DEFAULT;
    LightRedTimeOn = LIGHT_RED_TIME_ON_DEFAULT;
    TimeNeedToDisplay = 0;
    TrafficLightClearAll();
}
void TrafficLightSet(int color)
{
    switch (color)
    {
    case LIGHT_GREEN:
        HAL_GPIO_WritePin(GPIO_LIGHT_GREEN, GPIO_PIN_SET);
    break;
    case LIGHT_YELLOW:
        HAL_GPIO_WritePin(GPIO_LIGHT_YELLOW, GPIO_PIN_SET);
    break;
    case LIGHT_RED:
        HAL_GPIO_WritePin(GPIO_LIGHT_RED, GPIO_PIN_SET);
    break;
    default:
        HAL_GPIO_WritePin(GPIO_TRAFFIC_LIGHT_ALL, GPIO_PIN_SET);
    break;
    }
}

void SetLightState(int newState)
{
    LightState = newState;
}
int GetLightState(void)
{
    return LightState;
}
void TrafficLightClearAll(void)
{
    HAL_GPIO_WritePin(GPIO_TRAFFIC_LIGHT_ALL, GPIO_PIN_RESET);
}
void TrafficLightSetAll(void)
{
    HAL_GPIO_WritePin(GPIO_TRAFFIC_LIGHT_ALL, GPIO_PIN_SET);
}
void TrafficLightTest(void)
{
    int color = 0;
    for (color = 0; color < LIGHT_MAX; color++)
    {
        TrafficLightSet(color);
        HAL_Delay(300);
        TrafficLightClearAll();
    }
        
}
int GetTimeNeedToDisplay(void)
{
    return TimeNeedToDisplay;
}
void TrafficLightManager(void)
{
    int userMode = GetUserMode();

    switch (userMode)
    {
        case USER_MODE_NORMAL:
            TrafficLightRunAtNormal();
        break;
        case USER_MODE_ADJUST:
            TrafficLightRunAtAdjust();
        break;
        case USER_MODE_TEST:
        default:
        break;
    }
    
    TrafficLightSet(LightState);
}
void TrafficLightRunAtAdjust(void)
{
    int currentLightState = LightState;

    switch (LightState)
    {
    case LIGHT_GREEN:
        TimeNeedToDisplay = LightGreenTimeOn;
    break;
    case LIGHT_YELLOW:
        TimeNeedToDisplay = LightYellowTimeOn;
    break;
    case LIGHT_RED:
        TimeNeedToDisplay = LightRedTimeOn;
    break;
    default:
        TimeNeedToDisplay = 99;
    break;
    }


    
    // if ((flagIsBlink % 2) == 0)
    // {
    //     TrafficLightSet(LightState);
    // }
    // else
    // {
    //     TrafficLightClearAll();
    // }
}

void TrafficLightRunAtNormal(void)
{
    int systemTimer = GetSystemTimer1s();
    int currentLightState = LightState;

    switch (LightState)
    {
    case LIGHT_GREEN:
        if (systemTimer > LightGreenTimeOn)
        {
            LightState = LIGHT_YELLOW;
        }
        TimeNeedToDisplay = LightGreenTimeOn - systemTimer;
    break;
    case LIGHT_YELLOW:
        if (systemTimer > LightYellowTimeOn)
        {
            LightState = LIGHT_RED;
        }
        TimeNeedToDisplay = LightYellowTimeOn - systemTimer;
    break;
    case LIGHT_RED:
        if (systemTimer > LightRedTimeOn)
        {
            LightState = LIGHT_GREEN;
        }
        TimeNeedToDisplay = LightRedTimeOn - systemTimer;
    break;
    default:
        LightState = LIGHT_YELLOW;
    break;
    }
    

    if (LightState != currentLightState)
    {
        ReSetSystemTimer();
        TrafficLightClearAll();
    }
    
}
void AdjustLightTimeOn(int direction)
{
    switch (LightState)
    {
        case LIGHT_GREEN:
            if (direction == INCREASE)
            {
                LightGreenTimeOn++;
            }
            else
            {
                LightGreenTimeOn--;
            }
        break;
        case LIGHT_YELLOW:
            if (direction == INCREASE)
            {
                LightYellowTimeOn++;
            }
            else
            {
                LightYellowTimeOn--;
            }
        break;
        case LIGHT_RED:
            if (direction == INCREASE)
            {
                LightRedTimeOn++;
            }
            else
            {
                LightRedTimeOn--;
            }
        break;
        default:
        break;
    }
}